### ISSUE TITLE
Bro can you please help me the roullete program dont work any more can you please help me. :(

### ISSUE THREAD

**Issue by Hojasroulett** [tbaltrushaitis/cmdb-rtm#19]

**Comment by tbaltrushaitis** [comment]
Hi, @Hojasroulett!

Can you please describe your issue more detailed?
And FYI: this is NOT a roulette predictor repo :-)

Regards!

**Comment by Hojasroulett** [comment]
Dear Thomas, the problem has been solved, I just couldn't get to your
links, it didn't load, but now it's fine again, thank you for your
response, have a nice evening


Op vr 16 feb. 2024 om 05:35 schreef Tomas Baltrushaitis <
***@***.***>
